#
# Module manifest for module 'MicrosoftTeams'
#
# Generated by: Microsoft Corporation
#
# Generated on: 9/10/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = if($PSEdition -ne 'Desktop')
{
    'netstandard2.0\Microsoft.TeamsCmdlets.PowerShell.Custom.dll'
}
else
{
    'net472\Microsoft.TeamsCmdlets.PowerShell.Custom.dll'
}

# Version number of this module.
ModuleVersion = '1.0.5'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'd910df43-3ca6-4c9c-a2e3-e9f45a8e2ad9'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) 2020 Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Teams Cmdlets module'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
                'GetTeamSettings.format.ps1xml',
                'PolicyPackage.format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = if($PSEdition -ne 'Desktop')
{
    'netstandard2.0\Microsoft.Teams.PowerShell.Auth.dll',
    'netstandard2.0\Microsoft.TeamsCmdlets.PowerShell.Connect.dll',
    'netstandard2.0\Microsoft.TeamsCmdlets.PowerShell.Custom.dll',
    'Microsoft.Teams.Config.psd1'
}
else
{
    'net472\Microsoft.Teams.PowerShell.Auth.dll',
    'net472\Microsoft.TeamsCmdlets.PowerShell.Connect.dll',
    'net472\Microsoft.TeamsCmdlets.PowerShell.Custom.dll',
    'Microsoft.Teams.Config.psd1'
}

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Office365', 'MicrosoftTeams', 'Teams'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/Azure/azure-powershell/preview/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams'

        # A URL to an icon representing this module.
        IconUri = 'https://statics.teams.microsoft.com/evergreen-assets/apps/teamscmdlets_largeimage.png'

        # ReleaseNotes of this module
        ReleaseNotes = @'
## 1.0.5

This update includes:
- New-CsBatchPolicyAssignmentOperation - Assign a policy to a batch of users. A batch may contain up to 20,000 users.
- Get-CsBatchPolicyAssignmentOperation - Check state of each async batch policy assignment operation.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
